//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UpdateMyList.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class GenreGroup
    {
        public int gengroupId { get; set; }
        public int genId { get; set; }
        public int listId { get; set; }
        public string recStatus { get; set; }
        public Nullable<System.DateTime> createDate { get; set; }
        public string createBy { get; set; }
        public Nullable<System.DateTime> updateDate { get; set; }
        public string updateBy { get; set; }
    }
}
