//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UpdateMyList.Entity
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class myListEntities : DbContext
    {
        public myListEntities()
            : base("name=myListEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<StsMast> StsMasts { get; set; }
        public virtual DbSet<ListTypeMast> ListTypeMasts { get; set; }
        public virtual DbSet<MyListMast> MyListMasts { get; set; }
        public virtual DbSet<UserProfile> UserProfiles { get; set; }
    }
}
