//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UpdateMyList.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class MyListMast
    {
        public int listId { get; set; }
        public int listTypeId { get; set; }
        public Nullable<int> listCode { get; set; }
        public string listName { get; set; }
        public string listLink { get; set; }
        public string listEP { get; set; }
        public string listComment { get; set; }
        public int stsId { get; set; }
        public string recStatus { get; set; }
        public Nullable<System.DateTime> createDate { get; set; }
        public string createBy { get; set; }
        public Nullable<System.DateTime> updateDate { get; set; }
        public string updateBy { get; set; }
        public Nullable<int> seasonId { get; set; }
    }
}
